const data = {
    products: [
      {
        _id: '1',
        name: 'Nike Shoes',
        category: 'Shoes',
        image: '/img/mercurial-boot.jpeg',
        price: 120,
        countInStock: 10,
        brand: 'Nike',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality product',
      },
      {
        _id: '2',
        name: 'Nike Shoes',
        category: 'Shoes',
        image: '/img/air-jordan.jpeg',
        price: 120,
        countInStock: 10,
        brand: 'Nike',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality product',
      },
      {
        _id: '3',
        name: 'Nike Shoes',
        category: 'Shoes',
        image: '/img/air-jordan.jpeg',
        price: 120,
        countInStock: 10,
        brand: 'Nike',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality product',
      },
      {
        _id: '4',
        name: 'Nike Shoes',
        category: 'Shoes',
        image: '/img/Air.webp.png',
        price: 100,
        countInStock: 10,
        brand: 'Nike',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality product',
      },
      {
        _id: '5',
        name: 'Nike Shoes',
        category: 'Shoes',
        image: '/img/dawn-shoe.jpeg',
        price: 120,
        countInStock: 10,
        brand: 'Adidas',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality product',
      },
      {
        _id: '6',
        name: 'Nike Shoes',
        category: 'Shoes',
        image: '/img/s-l1600.jpeg',
        price: 120,
        countInStock: 10,
        brand: 'Nike',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality product',
      },
    ],
  };
  export default data;
  